#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings

# active_window_border_color   0xff1bd176 # green
# active_window_border_color   0xff8659cf # purp
# active_window_border_color   0xff3366ff # blue
# active_window_border_color   0xffFfc53c # yellow
# active_window_border_color   0xffFfa100 # Orange
# active_window_border_color   0xffE42810 # red

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    1.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff3366ff     \
    normal_window_border_color   0xff555555     \
    window_border_width          3              \
    window_border_radius         12             \
    window_border_blur           on            \
    window_border_hidpi          on             \
    window_border                on            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

echo "yabai configuration loaded.."
borders background_color=0x15ffffff active_color=0xffFfc53c inactive_color=0xff555555 width=3.0 blur_radius=30.0 &
